version: "3.8"

services:
  luften-forecast:
    build: .
    container_name: luften-forecast-api
    restart: unless-stopped
    ports:
      - "2385:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
# Optional: Add volume for logs if needed
# volumes:
#   luften-logs:
#     driver: local
